site_name: RingCentral Embeddable Phone for HubSpot
site_url: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone
site_description: A Google Chrome extension that enables click-to-dial functionality from RingCentral in HubSpot. 

repo_url: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone

plugins:
  - search
  - bootstrap-tables

theme:
  name: moonstone
  custom_dir: 'theme/'
  fluid_layout: False

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - codehilite:
      linenums: "None"

nav:
  - Home: index.md
  - Installation: install.md
  - Customization: developers.md
  - About: about.md

extra_css:
    - css/extra.css

copyright: Copyright 2019 RingCentral Inc. 
google_analytics: 
